# Generated by Django 5.0.6 on 2024-06-23 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_userprofile'),
        ('core', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='compte.userprofile'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='passager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='compte.userprofile'),
        ),
        migrations.AlterField(
            model_name='driverrating',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='compte.userprofile'),
        ),
        migrations.AlterField(
            model_name='driverrating',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='compte.userprofile'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='conducteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets_proposes', to='compte.userprofile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='compte.userprofile'),
        ),
        migrations.AlterField(
            model_name='recompense',
            name='conducteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompenses', to='compte.userprofile'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='compte.userprofile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
